---
# tasks file for user
- name: tworzenie grupy panda
  group:
    name: panda
    state: present

- name: tworzenie uzytkownika panda
  user:
    name: panda
    shell: /bin/bash
    groups:
      - panda
      - sudo

- name: kopiowanie klucza ssh z vagrant do panda
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
    path: /home/panda/.ssh/authorized_keys
